# Generated by Django 3.0.4 on 2020-03-28 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackablePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('staff', 'Staff'), ('patient', 'Patient'), ('other', 'Other')], max_length=12)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('at_risk', 'At Risk'), ('being_tested', 'Being Tested'), ('infected', 'Infected')], max_length=12)),
            ],
            options={
                'db_table': 'ethermed_trackable_person',
            },
        ),
        migrations.CreateModel(
            name='TrackingTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'ethermed_tracking_tag',
            },
        ),
        migrations.CreateModel(
            name='TagPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='inftrackapp.TrackablePerson')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='inftrackapp.TrackingTag')),
            ],
            options={
                'db_table': 'ethermed_tag_position',
            },
        ),
        migrations.CreateModel(
            name='TagAssignmentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned')], max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='inftrackapp.TrackablePerson')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignments', to='inftrackapp.TrackingTag')),
            ],
            options={
                'db_table': 'ethermed_tag_assignment_event',
            },
        ),
        migrations.CreateModel(
            name='StatusChangeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('prior_status', models.CharField(choices=[('ok', 'Ok'), ('at_risk', 'At Risk'), ('being_tested', 'Being Tested'), ('infected', 'Infected')], max_length=12)),
                ('new_status', models.CharField(choices=[('ok', 'Ok'), ('at_risk', 'At Risk'), ('being_tested', 'Being Tested'), ('infected', 'Infected')], max_length=12)),
                ('timestamp', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_change_events', to='inftrackapp.TrackablePerson')),
            ],
            options={
                'db_table': 'ethermed_status_change_event',
            },
        ),
    ]
