# Generated by Django 2.2.5 on 2020-03-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inftrackapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagassignmentevent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignment_events', to='inftrackapp.TrackablePerson'),
        ),
        migrations.AlterField(
            model_name='tagassignmentevent',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_assignment_events', to='inftrackapp.TrackingTag'),
        ),
    ]
